### ISSUE TITLE
[Date Picker] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#19]
## Componente Date Picker

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by PatricioRios** [comment]
hola aris, quiero asignarme el date picker, no tengo experiencia alguna con astro, pero hare lo que pueda, por si no me asignas la tarea a mi y la hace otro le dejo la doc 
https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#DatePicker(androidx.compose.material3.DatePickerState,androidx.compose.ui.Modifier,androidx.compose.material3.DatePickerFormatter,kotlin.Function0,kotlin.Function0,kotlin.Boolean,androidx.compose.material3.DatePickerColors)

**Comment by ArisGuimera** [comment]
Te la puedes asignar tu mismo a la derecha :)

**Comment by PatricioRios** [comment]
hola aris, que no me deja asignarme la issue como hiciste en el video

**Comment by ArisGuimera** [comment]
> hola aris, no me deja asignarme la issue como hiciste en el video, vi en el discord y hay otros que tampoco les permite

Te la asigno!
