### ISSUE TITLE
[Text Field] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#21]
## Componente Text Field

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by S-H-U-R-A** [comment]
Hola Aris me gustaría colaborar en el proyecto junto con mi esposa me podrías agregar.

**Comment by 006900** [comment]
hola aris me gustaria añadir un OutlinedTextField con funcionalidades extra como la limitacion de caracteres

**Comment by ArisGuimera** [comment]
No podéis asignaros la tarea ustedes mismos? Es para saber si tengo que tocar algo haha

**Comment by CamaronProductions** [comment]
hola aris. Genial proyecto!!! me encantaria colaborar, pero no me deja asignarme tareas. Aunque no se si el fallo es mio.

**Comment by ArisGuimera** [comment]
Parece que gitHub no deja asignar a los que no son owner, si quieres busca una issue que no haya pedido nadie y te la asigno

**Comment by ArisGuimera** [comment]
> hola aris me gustaria añadir un OutlinedTextField con funcionalidades extra como la limitacion de caracteres

Podría ser un ejemplo del TextField cuando esté hecho o crear otro componente, qué opinas?

**Comment by CamaronProductions** [comment]
Me parece genial el ejemplo de textfield. para empezar. Gracias!

**Comment by ArisGuimera** [comment]
Se libera la tarea por inactividad del owner

**Comment by SirMartyCode** [comment]
Hola Aris, me gustaría participar en el proyecto, me la puedes asignar?

**Comment by ArisGuimera** [comment]
> Hola Aris, me gustaría participar en el proyecto, me la puedes asignar?

Tuya!

**Comment by SirMartyCode** [comment]
> > Hola Aris, me gustaría participar en el proyecto, me la puedes asignar?
> 
> Tuya!

Aris necesito algun permiso especial para hacer push de mi rama?

Me sale este error:

_ERROR: Permission to ArisGuimera/JetpackComposePro.git denied to SirMartyCode.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists._

**Comment by ArisGuimera** [comment]
> > > Hola Aris, me gustaría participar en el proyecto, me la puedes asignar?
> > 
> > 
> > Tuya!
> 
> @ArisGuimera necesito algun permiso especial para hacer push de mi rama?
> 
> Me sale este error:
> 
> _ERROR: Permission to ArisGuimera/JetpackComposePro.git denied to SirMartyCode. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists._

Tienes que hacer una PR, no puedes pushearlo directamente

**Comment by ArisGuimera** [comment]
Tarea cerrada, gracias a @SirMartyCode
