### ISSUE TITLE
[Outlined Text Field] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#22]
## Componente Outlined Text Field

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by alejandro342** [comment]
Hola Aris que tal?, Me agregas como colaborador? Me gustaria aportar mi granito de arena a la comunidad.

**Comment by ArisGuimera** [comment]
Buenas, a la derecha en "Assignees" no te permite añadirte?

**Comment by alejandro342** [comment]
no, no me deja.

**Comment by ArisGuimera** [comment]
Te la asigno

**Comment by alejandro342** [comment]
Gracias

**Comment by alejandro342** [comment]
Ya terminé la documentación de ambos casos material y material 3

**Comment by ArisGuimera** [comment]
> Ya terminé la documentación de ambos casos material y material 3

Perfecto, cuando se mergee la PR cerramos esta issue!
