### ISSUE TITLE
[IconButton] -  Añadir documentación del componente 

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#25]
## Componente IconButton

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by IsTheMartin** [comment]
Buenas @ArisGuimera, qué tal? Puedes asignarme este issue por favor?

**Comment by ArisGuimera** [comment]
> Buenas @ArisGuimera, qué tal? Puedes asignarme este issue por favor?

Era mía, pero te la paso :)

**Comment by IsTheMartin** [comment]
Hola @ArisGuimera !
Se puede cerrar este issue? O hace falta algo más para agregar? 🤔

**Comment by ArisGuimera** [comment]
> Hola @ArisGuimera ! Se puede cerrar este issue? O hace falta algo más para agregar? 🤔

Cerrada!
