### ISSUE TITLE
[RadioButton] esta tambien no tiene mucho misterio  

### ISSUE THREAD

**Issue by 006900** [ArisGuimera/JetpackComposePro#37]
este botton nos sirve mas que nada para cuando tenemos multiples preguntas pero solo queremos seleccionar una sola
![Captura de pantalla (104)](https://github.com/ArisGuimera/JetpackComposePro/assets/142174731/15087248-578f-4335-9eb6-b39bdea8e28f)

**Comment by alexRai98** [comment]
Hola @ArisGuimera puedo colaborar desarrollando esta issue?

**Comment by ArisGuimera** [comment]
> Hola @ArisGuimera puedo colaborar desarrollando esta issue?

El radiobutton ya está hecho! https://www.jetpackcompose.pro/buttons/radio-button/
