### ISSUE TITLE
[SwipeToDismiss]

### ISSUE THREAD

**Issue by 006900** [ArisGuimera/JetpackComposePro#38]

**Comment by enocgarcia2005** [comment]
@ArisGuimera puedo trabajar esta issue?

**Comment by ArisGuimera** [comment]
> @ArisGuimera puedo trabajar esta issue?

Te la asigno!

**Comment by enocgarcia2005** [comment]
@ArisGuimera Puedes cerrar la issue porfa, a mi no me deja
