### ISSUE TITLE
[SwipeRefresh]

### ISSUE THREAD

**Issue by 006900** [ArisGuimera/JetpackComposePro#39]

**Comment by CalderonRigoberto** [comment]
Hola @ArisGuimera  me gustaría colaborar con la documentación para este componente.

**Comment by RubenNarvaez** [comment]
Hola, me gustaria trabahar en este componente

**Comment by enocgarcia2005** [comment]
@ArisGuimera Puedo trabajar esta issue?

**Comment by ArisGuimera** [comment]
Asignado @enocgarcia2005 !

**Comment by enocgarciadev** [comment]
@ArisGuimera Issue Completada!

**Comment by ArisGuimera** [comment]
Eres un crack!
