### ISSUE TITLE
Cards components

### ISSUE THREAD

**Issue by jamirou** [ArisGuimera/JetpackComposePro#46]
Hola Aris me agregas como colaborador para actualizar el componente Card? Ya está casi todo listo 🖖

**Comment by ArisGuimera** [comment]
El componente card ya tiene dueño!

https://github.com/ArisGuimera/JetpackComposePro/pull/4

**Comment by jamirou** [comment]
Jaja gracias Aris, y el componente Circular Progress Indicator tiene dueño?

**Comment by ArisGuimera** [comment]
> Jaja gracias Aris, y el componente Circular Progress Indicator tiene dueño?

Nop, puedes crear una tarea y te la asigno si quieres!
