### ISSUE TITLE
[LazyColumn] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#53]
## Componente LazyColumn

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by SantipBarber** [comment]
Buenas! Esta no estaba entre las que comenté en discussions, pero me parece súper interesante. No me la puedo auto asignar. Me la asignas, plis? Un saludo

**Comment by ArisGuimera** [comment]
> Buenas! Esta no estaba entre las que comenté en discussions, pero me parece súper interesante. No me la puedo auto asignar. Me la asignas, plis? Un saludo

Claro, ya la tienes!
