### ISSUE TITLE
[DropdownMenuItem] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#56]
## Componente DropdownMenuItem

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by jamirou** [comment]
Me asignas esta issue Aris por favor :)

**Comment by ArisGuimera** [comment]
> Me asignas esta issue Aris por favor :)

Claro!!

**Comment by Iptriana98** [comment]
Hola Aris, me asignas esta issue plis 🙏

**Comment by ArisGuimera** [comment]
> Hola Aris, me asignas esta issue plis 🙏

Tuya!

**Comment by ArisGuimera** [comment]
Cierro aquí, gracias @Iptriana98
