### ISSUE TITLE
[DropdownMenu] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#57]
## Componente DropdownMenu

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by ernesto-ca** [comment]
Hola Aris! me gastaría poyar en la documentación de este ya que recientemente he trabajado mucho con este componente, muchas gracias por este proyecto que conozco a muchos compañeros que les servirá! A TODA LATAM!

**Comment by ArisGuimera** [comment]
> mentación de este ya que recientemente he trabajado mucho con este componente, muchas gracias por este

Muchísimas gracias! Ya lo tienes asignado :)
