### ISSUE TITLE
[Circular Progress Indicator] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#58]
## Componente Circular Progress Indicator

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by MarcoServinDLT** [comment]
¡Hola! Me encantaría poder colaborar con la documentación correspondiente a este componente.

**Comment by ArisGuimera** [comment]
> ¡Hola! Me encantaría poder colaborar con la documentación correspondiente a este componente.

Todo tuyo, ya lo tienes asignado 💪
