### ISSUE TITLE
Chip

### ISSUE THREAD

**Issue by OrlanDroyd** [ArisGuimera/JetpackComposePro#6]
Documentación del elemento `Chip`

**Comment by LucasGinard** [comment]
🙋‍♂️ quiero llevarlo me asignas porfa

**Comment by OrlanDroyd** [comment]
Vale, recién empezaba 😅
Me pongo a adelantar otro componente :)

**Comment by LucasGinard** [comment]
Una disculpa pense que lanzaste el issue sobre lo que faltaba no que ibas a llevarlo 😅
ya se puede cerrar el issue por el pull request #9

**Comment by OrlanDroyd** [comment]
Aris debe aprobarlo antes ;)

**Comment by ArisGuimera** [comment]
Mergeado, cerramos issue 🙌🏻

Gracias!
