### ISSUE TITLE
[Side sheet] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#60]
## Componente Side sheet

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by siemprecubano89** [comment]
hola aris, me gustaría colaborar con esta issue

**Comment by enocgarciadev** [comment]
@ArisGuimera Puedo trabajar esta issue?

**Comment by ArisGuimera** [comment]
> @ArisGuimera Puedo trabajar esta issue?

Tuya!

**Comment by enocgarciadev** [comment]
@ArisGuimera Issue completada!
