### ISSUE TITLE
[Tab] - Añadir documentación del componente

### ISSUE THREAD

**Issue by ArisGuimera** [ArisGuimera/JetpackComposePro#64]
## Componente Tab

Estoy añadiendo todos los componentes que faltan por añadir para que no nos pisemos a la hora de seleccionar alguno. Si te interesa realizar este componente simplemente asígnate la tarea (arriba a la derecha).

En el [README](https://github.com/ArisGuimera/JetpackComposePro/blob/master/README.md) tienes toda la info necesaria para realizar la documentación.

Desde ya muchas gracias por colaborar con la comunidad :)

**Comment by ronald-bismar** [comment]
Podrías asignarme esta issue @ArisGuimera

**Comment by ArisGuimera** [comment]
> Podrías asignarme esta issue @ArisGuimera

Listo 💪🏼

**Comment by ronald-bismar** [comment]
@ArisGuimera Listos los cambios de la documentación del componente Tab

**Comment by ArisGuimera** [comment]
https://github.com/ArisGuimera/JetpackComposePro/pull/106

Completa
