### ISSUE TITLE
[DatePickerDialog] - Añadir documentación del componente

### ISSUE THREAD

**Issue by PatricioRios** [ArisGuimera/JetpackComposePro#74]
## Componente DatePickerDialog

Buenas, quiero añadir el componente DatePickerDialog, necesito saber si voy a ser el encargado de hacerlo,
de ser así tengo una duda, en que parte se agregara el DatePickerDialog, en la sección de Dialogs ? , o una nueva sección ?, o talvez seria mejor crear una nueva sección para colocar el DatePickerDialog, junto a el DatePicker?

**Comment by ArisGuimera** [comment]
DatePickerDialog no es un composable, es de XML.

Un saludo
